[build]
  publish = "dist/"
  command = "npm run generate"
  [context.deploy-preview]
    ignore = "git log -1 --pretty=%B | grep dependabot"

[[redirects]]
  from = "/*"
  to = "https://www.svenjungnickel.dev/:splat"
  status = 301
  force = true
  conditions = { Host = ["svenjungnickel.com", "www.svenjungnickel.com", "svenjungnickel.de", "www.svenjungnickel.de", "svenjungnickel.dev"] }
