[build]
  publish = "dist/"
  command = "npm run generate"
  [context.deploy-preview]
    ignore = "git log -1 --pretty=%B | grep dependabot"

[[redirects]]
  from = "https://svenjungnickel.com/*"
  to = "https://www.svenjungnickel.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.svenjungnickel.com/*"
  to = "https://www.svenjungnickel.dev/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://svenjungnickel.de/*"
  to = "https://www.svenjungnickel.dev/:splat"
  status = 301
  force = true
[[redirects]]
   from = "https://www.svenjungnickel.de/*"
   to = "https://www.svenjungnickel.dev/:splat"
   status = 301
   force = true
